"""Exhaustive ISA golden: interpreter vs emitted Verilog, every encoding.

Every (opcode, field, payload) triple -- all 2048 -- runs on the generated
`src/loom_engine.v` under iverilog and on `loom.interp.SM`, from a fixed
non-trivial preamble state, under three gpio_in stimuli (all-0, all-1,
random) and delay fields 0, 1 and 31 (random stimulus only). Full
architectural state is compared every cycle: pc, x, y, osr, isr, gpio_out,
gpio_oe, tx_full, rx_empty and the RX head byte.

Vectors are generated by the interpreter and checked inside the Verilog
testbench, so the whole sweep is one iverilog run.
"""

from __future__ import annotations

import os
import random
import shutil
import subprocess
from pathlib import Path

import pytest

from loom.isa import (
    FIFO_PULL,
    OP_FIFO,
    OP_IN,
    OP_SET,
    SET_INPIN,
    SET_OUTPIN,
    SET_PINDIRS,
    SET_PINS,
    SET_X,
    SET_Y,
    SHIFT_MSB,
    encode,
)
from loom.interp import SM

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "src" / "loom_engine.v"
GEN = ROOT / "test" / "gen"
IMAGE = "ghcr.io/librelane/librelane:3.1.0.dev3"

PREAMBLE = [
    encode(OP_SET, 0, SET_PINDIRS, 0b01010),
    encode(OP_SET, 0, SET_PINS, 0b10101),
    encode(OP_SET, 0, SET_X, 5),
    encode(OP_SET, 0, SET_Y, 3),
    encode(OP_SET, 0, SET_OUTPIN, 3),
    encode(OP_SET, 0, SET_INPIN, 2),
    encode(OP_FIFO, 0, FIFO_PULL, 0),
    encode(OP_IN, 0, SHIFT_MSB, 1),
]
TX_BYTES = (0xA5, 0x3C)
TAIL = 4  # cycles observed after the instruction's own delay


def _snap(sm: SM) -> int:
    head = 0 if sm.rx.empty else sm.rx.q[0]
    v = sm.pc & 31
    for fld in (sm.x, sm.y, sm.osr, sm.isr, sm.out_reg, sm.oe_reg):
        v = (v << 8) | (fld & 0xFF)
    v = (v << 1) | int(sm.tx.full)
    v = (v << 1) | int(sm.rx.empty)
    v = (v << 8) | (head & 0xFF)
    return v


def _cases():
    rng = random.Random(0xC0FFEE)
    for op in range(8):
        for field in range(8):
            for payload in range(32):
                for delay in (0, 1, 31):
                    stims = ("rand",) if delay == 31 else ("zero", "ones", "rand")
                    for stim in stims:
                        instr = encode(op, delay, field, payload)
                        ncyc = len(PREAMBLE) + 1 + delay + TAIL
                        if stim == "zero":
                            gin = [0x00] * ncyc
                        elif stim == "ones":
                            gin = [0xFF] * ncyc
                        else:
                            gin = [rng.getrandbits(8) for _ in range(ncyc)]
                        yield instr, gin


def _expected(instr: int, gin: list[int]) -> list[int]:
    sm = SM()
    sm.load(PREAMBLE + [instr])
    for b in TX_BYTES:
        sm.tx.push(b)
    sm.run = True
    out = []
    for g in gin:
        sm.tick(g)
        out.append(_snap(sm))
    return out


TB = """`timescale 1ns/1ps
module tb;
  reg clk = 0, rst = 1, run = 0, imem_we = 0, tx_we = 0, rx_re = 0;
  reg [4:0] waddr = 0; reg [15:0] wdata = 0; reg [7:0] tx_data = 0, gpio_in = 0;
  wire [7:0] gpio_out, gpio_oe, rx_data; wire tx_full, rx_empty; wire [4:0] pc;
  always #10 clk = ~clk;
  loom_engine dut (
    .clk(clk), .rst(rst), .run(run), .gpio_in(gpio_in), .gpio_out(gpio_out), .gpio_oe(gpio_oe),
    .imem_we(imem_we), .imem_waddr(waddr), .imem_wdata(wdata),
    .imem_slot(2'b00), .sm_sel(1'b0), .csr_we(1'b0), .csr_addr(5'b0), .csr_wdata(8'h00),
    .tx_we(tx_we), .tx_data(tx_data), .tx_full(tx_full),
    .rx_re(rx_re), .rx_data(rx_data), .rx_empty(rx_empty), .pc(pc));
  reg [15:0] PRE [0:%(npre)d];
  reg [47:0] CASES [0:%(ncase)d];
  reg [7:0]  GIN [0:%(nvec)d];
  reg [62:0] EXP [0:%(nvec)d];
  integer c, i, k, fails, start, ncyc; reg [15:0] instr; reg [62:0] got;
  initial begin
    $readmemh("%(gen)s/isa_pre.hex", PRE);
    $readmemh("%(gen)s/isa_cases.hex", CASES);
    $readmemh("%(gen)s/isa_gin.hex", GIN);
    $readmemh("%(gen)s/isa_exp.hex", EXP);
    fails = 0;
    // Warm-up: push one byte and pop it so the rx_data read mux (an always @*
    // block) has been evaluated once. iverilog never runs such a block until an
    // input changes; a first push of 0x00 into a 0x00-initialised slot with
    // rx_r stuck at 0 would otherwise read X. Simulation artifact, not RTL.
    @(negedge clk); @(negedge clk); rst = 0;
    @(negedge clk); imem_we = 1; waddr = 0; wdata = 16'h8000;
    @(negedge clk); imem_we = 0; run = 1;
    @(negedge clk); @(negedge clk); run = 0; rx_re = 1;
    @(negedge clk); rx_re = 0;
    for (c = 0; c < %(ncase)d; c = c + 1) begin
      instr = CASES[c][47:32]; ncyc = CASES[c][31:24]; start = CASES[c][23:0];
      @(negedge clk); rst = 1; run = 0; imem_we = 0; tx_we = 0;
      @(negedge clk); @(negedge clk); rst = 0;
      for (i = 0; i <= %(npre)d; i = i + 1) begin
        @(negedge clk); imem_we = 1; waddr = i[4:0]; wdata = (i == %(npre)d) ? instr : PRE[i];
      end
      @(negedge clk); imem_we = 0; tx_we = 1; tx_data = 8'h%(tx0)02x;
      @(negedge clk); tx_data = 8'h%(tx1)02x;
      @(negedge clk); tx_we = 0;
      for (k = 0; k < ncyc; k = k + 1) begin
        @(negedge clk); run = 1; gpio_in = GIN[start + k];
        @(posedge clk); #1;
        got = {pc, dut.x, dut.y, dut.osr, dut.isr, gpio_out, gpio_oe, tx_full, rx_empty,
               (rx_empty ? 8'h00 : rx_data)};
        if (got !== EXP[start + k]) begin
          fails = fails + 1;
          if (fails <= 20)
            $display("MISMATCH case=%%0d instr=%%04x cyc=%%0d rtl=%%016x exp=%%016x", c, instr, k, got, EXP[start + k]);
        end
      end
      @(negedge clk); run = 0;
    end
    if (fails == 0) $display("PASS cases=%%0d", %(ncase)d);
    else $display("FAIL mismatches=%%0d", fails);
    $finish;
  end
endmodule
"""


def _write_vectors() -> int:
    GEN.mkdir(parents=True, exist_ok=True)
    cases, gin, exp = [], [], []
    for instr, g in _cases():
        start = len(gin)
        cases.append((instr, len(g), start))
        gin.extend(g)
        exp.extend(_expected(instr, g))
    (GEN / "isa_pre.hex").write_text("".join(f"{w:04x}\n" for w in PREAMBLE))
    (GEN / "isa_cases.hex").write_text(
        "".join(f"{(i << 32) | (n << 24) | s:012x}\n" for i, n, s in cases)
    )
    (GEN / "isa_gin.hex").write_text("".join(f"{b:02x}\n" for b in gin))
    (GEN / "isa_exp.hex").write_text("".join(f"{v:016x}\n" for v in exp))
    (GEN / "tb_isa_exhaustive.v").write_text(
        TB
        % dict(
            npre=len(PREAMBLE),
            ncase=len(cases),
            nvec=len(gin),
            gen=GEN.relative_to(ROOT).as_posix(),
            tx0=TX_BYTES[0],
            tx1=TX_BYTES[1],
        )
    )
    return len(cases)


def _iverilog(args: list[str]) -> str:
    """Run `iverilog ... && vvp` from ROOT, natively or in the LibreLane image."""
    if shutil.which("iverilog") and shutil.which("vvp"):
        subprocess.run(["iverilog", "-g2012", "-o", "test/gen/isa.vvp", *args], cwd=ROOT, check=True)
        r = subprocess.run(["vvp", "-n", "test/gen/isa.vvp"], cwd=ROOT, check=True, capture_output=True, text=True)
        return r.stdout
    if not shutil.which("docker"):
        pytest.skip("needs iverilog or docker")
    script = (
        'export PATH="$(dirname $(ls /nix/store/*iverilog-13*/bin/iverilog | head -1)):$PATH"; '
        f"iverilog -g2012 -o test/gen/isa.vvp {' '.join(args)} && vvp -n test/gen/isa.vvp"
    )
    r = subprocess.run(
        ["docker", "run", "--rm", "-u", f"{os.getuid()}:{os.getgid()}", "-v", f"{ROOT}:/work", "-w", "/work",
         "--entrypoint", "/bin/sh", IMAGE, "-c", script],
        check=True, capture_output=True, text=True,
    )
    return r.stdout


def test_verilog_isa_exhaustive():
    n = _write_vectors()
    assert n == 8 * 8 * 32 * 7
    out = _iverilog(["src/loom_engine.v", "test/gen/tb_isa_exhaustive.v"])
    lines = [l for l in out.splitlines() if l.startswith(("PASS", "FAIL", "MISMATCH"))]
    assert lines and lines[-1].startswith("PASS"), "\n".join(lines[:25])
