"""Emit Tiny Tapeout Verilog from the graph engine."""

from __future__ import annotations

from pathlib import Path

from amaranth.back import verilog

from loom.criteria import assert_engine_has_no_protocol_names, assert_pin_and_time_primitives
from loom.rtl import GraphEngine

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
TOP = "tt_um_loom_gpe"


def engine_verilog() -> str:
    dut = GraphEngine()
    ports = [
        dut.run,
        dut.gpio_in,
        dut.gpio_out,
        dut.gpio_oe,
        dut.imem_we,
        dut.imem_waddr,
        dut.imem_wdata,
        dut.tx_we,
        dut.tx_data,
        dut.tx_full,
        dut.rx_re,
        dut.rx_data,
        dut.rx_empty,
        dut.pc,
    ]
    return verilog.convert(dut, name="loom_engine", ports=ports)


WRAPPER = f"""
`default_nettype none

// Host protocol. clk sampled; rst_n active-low (engine rst = ~rst_n).
//   ui_in[0]     run
//   ui_in[1]     imem write strobe (rising edge, two-phase)
//   ui_in[6:2]   imem address, latched on the low-byte strobe
//   ui_in[7]     TX FIFO push strobe (rising edge)
//   uio_in[7:0]  data byte while run=0; GPIO in while run=1
//   uo_out[0]    run
//   uo_out[1]    tx_full
//   uo_out[2]    rx_empty
//   uo_out[7:3]  pc
// Load 16-bit word W at address A (run=0; do not pulse tx the same cycle):
//   1. uio_in=W[7:0],  ui_in[6:2]=A, pulse ui_in[1] (0→1 ≥1 clk →0 ≥1 clk)
//   2. uio_in=W[15:8], pulse ui_in[1] again (commits {{W[15:8], W[7:0]}} to imem[A])
// Push TX byte B (run=0; depth 4; skip if uo_out[1]==1):
//   3. uio_in=B, pulse ui_in[7]
// Run:
//   4. ui_in[0]=1  (uio becomes GPIO; uio_oe follows the graph)
module {TOP} (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
  wire rst = ~rst_n;
  wire run = ui_in[0];
  wire we  = ui_in[1] & ~run;
  wire txp = ui_in[7] & ~run;

  reg we_d, tx_d, hi;
  reg [4:0] addr;
  reg [7:0] lo;
  always @(posedge clk) begin
    if (rst) begin
      we_d <= 0;
      tx_d <= 0;
      hi <= 0;
      addr <= 0;
      lo <= 0;
    end else begin
      we_d <= we;
      tx_d <= txp;
      if (run) begin
        hi <= 0;
      end else if (we & ~we_d) begin
        if (!hi) begin
          addr <= ui_in[6:2];
          lo <= uio_in;
          hi <= 1;
        end else begin
          hi <= 0;
        end
      end
    end
  end

  wire imem_we = we & ~we_d & hi;
  wire tx_we   = txp & ~tx_d;
  wire [15:0] imem_wdata = {{uio_in, lo}};

  wire [7:0] gpio_out, gpio_oe, rx_data;
  wire tx_full, rx_empty;
  wire [4:0] pc;

  loom_engine engine (
    .clk(clk),
    .rst(rst),
    .run(run),
    .gpio_in(uio_in),
    .gpio_out(gpio_out),
    .gpio_oe(gpio_oe),
    .imem_we(imem_we),
    .imem_waddr(addr),
    .imem_wdata(imem_wdata),
    .tx_we(tx_we),
    .tx_data(uio_in),
    .tx_full(tx_full),
    .rx_re(1'b0),
    .rx_data(rx_data),
    .rx_empty(rx_empty),
    .pc(pc)
  );

  assign uio_out = gpio_out;
  assign uio_oe  = run ? gpio_oe : 8'h00;
  assign uo_out  = {{pc, rx_empty, tx_full, run}};
  wire _unused = &{{ena, rx_data, 1'b0}};
endmodule
"""


# Verilator -Wall style categories that Amaranth/Yosys-generated Verilog trips
# by construction. None is a functional issue; the engine is checked by the
# exhaustive ISA golden (every encoding, interp vs this file under iverilog)
# and by k-induction (loom formal). Scoped to this generated file only.
#   WIDTHTRUNC/WIDTHEXPAND  yosys writes `x == 0` as `!x`, `sig >> n` into 1-bit nets
#   PROCASSINIT             every flop has an `init` value *and* a sync reset
#   UNUSEDSIGNAL            carry/overflow bits of widened adders, unused SM handles
#   CASEINCOMPLETE          Array element writes are `casez` without default
LINT_OFF = ("WIDTHTRUNC", "WIDTHEXPAND", "PROCASSINIT", "UNUSEDSIGNAL", "CASEINCOMPLETE")
LINT_HEADER = (
    "/* Generated by loom.emit — do not edit. */\n"
    "/* verilator lint_off " + " */\n/* verilator lint_off ".join(LINT_OFF) + " */\n"
)
LINT_FOOTER = "/* verilator lint_on " + " */\n/* verilator lint_on ".join(LINT_OFF) + " */\n"


def emit() -> Path:
    assert_engine_has_no_protocol_names()
    assert_pin_and_time_primitives()
    engine = engine_verilog()
    (SRC / "loom_engine.v").write_text(LINT_HEADER + engine + LINT_FOOTER)
    (SRC / "project.v").write_text(
        "/* Generated wrapper. Graph programs load at runtime. */\n" + WRAPPER
    )
    return SRC / "project.v"


def main() -> None:
    print(emit())
    print(SRC / "loom_engine.v")


if __name__ == "__main__":
    main()
