/* Generated by loom.emit — do not edit. */
/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post128, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:58" *)
(* generator = "Amaranth" *)
module loom_engine(gpio_in, imem_we, imem_waddr, imem_wdata, tx_we, tx_data, rx_re, clk, rst, gpio_out, gpio_oe, tx_full, rx_data, rx_empty, pc, run);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire \$10 ;
  reg [15:0] \$100 ;
  reg [7:0] \$101 ;
  reg [7:0] \$102 ;
  reg [7:0] \$103 ;
  reg [7:0] \$104 ;
  reg [1:0] \$105 ;
  reg [2:0] \$106 ;
  reg [1:0] \$107 ;
  reg [1:0] \$108 ;
  reg [2:0] \$109 ;
  wire \$11 ;
  reg [1:0] \$110 ;
  reg [4:0] \$111 ;
  reg [7:0] \$112 ;
  reg [7:0] \$113 ;
  reg [7:0] \$114 ;
  reg [7:0] \$115 ;
  reg [7:0] \$116 ;
  reg [7:0] \$117 ;
  reg [7:0] \$118 ;
  reg [7:0] \$119 ;
  wire [5:0] \$12 ;
  reg [7:0] \$120 ;
  reg [7:0] \$121 ;
  reg [2:0] \$122 ;
  reg [2:0] \$123 ;
  reg [4:0] \$124 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire [7:0] \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire [2:0] \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire [3:0] \$30 ;
  wire [3:0] \$31 ;
  wire [2:0] \$32 ;
  wire [2:0] \$33 ;
  wire \$34 ;
  wire \$35 ;
  wire \$36 ;
  wire \$37 ;
  wire [3:0] \$38 ;
  wire [3:0] \$39 ;
  wire \$4 ;
  wire [2:0] \$40 ;
  wire \$41 ;
  wire [5:0] \$42 ;
  wire \$43 ;
  wire [8:0] \$44 ;
  wire \$45 ;
  wire [8:0] \$46 ;
  wire \$47 ;
  wire \$48 ;
  wire [7:0] \$49 ;
  wire \$5 ;
  wire [7:0] \$50 ;
  wire [7:0] \$51 ;
  wire [7:0] \$52 ;
  wire \$53 ;
  wire [7:0] \$54 ;
  wire [8:0] \$55 ;
  wire \$56 ;
  wire \$57 ;
  wire \$58 ;
  wire \$59 ;
  wire \$6 ;
  wire \$60 ;
  reg [7:0] \$61 ;
  wire \$62 ;
  wire [7:0] \$63 ;
  wire [7:0] \$64 ;
  wire [7:0] \$65 ;
  wire [7:0] \$66 ;
  wire [7:0] \$67 ;
  wire \$68 ;
  reg [15:0] \$69 ;
  wire \$7 ;
  reg [15:0] \$70 ;
  reg [15:0] \$71 ;
  reg [15:0] \$72 ;
  reg [15:0] \$73 ;
  reg [15:0] \$74 ;
  reg [15:0] \$75 ;
  reg [15:0] \$76 ;
  reg [15:0] \$77 ;
  reg [15:0] \$78 ;
  reg [15:0] \$79 ;
  wire \$8 ;
  reg [15:0] \$80 ;
  reg [15:0] \$81 ;
  reg [15:0] \$82 ;
  reg [15:0] \$83 ;
  reg [15:0] \$84 ;
  reg [15:0] \$85 ;
  reg [15:0] \$86 ;
  reg [15:0] \$87 ;
  reg [15:0] \$88 ;
  reg [15:0] \$89 ;
  wire \$9 ;
  reg [15:0] \$90 ;
  reg [15:0] \$91 ;
  reg [15:0] \$92 ;
  reg [15:0] \$93 ;
  reg [15:0] \$94 ;
  reg [15:0] \$95 ;
  reg [15:0] \$96 ;
  reg [15:0] \$97 ;
  reg [15:0] \$98 ;
  reg [15:0] \$99 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/.venv/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:66" *)
  reg [4:0] delay_ctr = 5'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:125" *)
  reg do_pull;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:123" *)
  wire do_pull0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:126" *)
  reg do_push;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:124" *)
  wire do_push0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:159" *)
  wire [7:0] eff;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:41" *)
  input [7:0] gpio_in;
  wire [7:0] gpio_in;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:43" *)
  output [7:0] gpio_oe;
  reg [7:0] gpio_oe = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:42" *)
  output [7:0] gpio_out;
  reg [7:0] gpio_out = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:134" *)
  wire host_rx;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:133" *)
  wire host_tx;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:45" *)
  input [4:0] imem_waddr;
  wire [4:0] imem_waddr;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:46" *)
  input [15:0] imem_wdata;
  wire [15:0] imem_wdata;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:44" *)
  input imem_we;
  wire imem_we;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:68" *)
  reg [2:0] in_pin = 3'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:70" *)
  reg [15:0] instr;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:65" *)
  reg [7:0] isr = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw0 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw1 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw10 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw11 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw12 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw13 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw14 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw15 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw16 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw17 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw18 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw19 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw2 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw20 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw21 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw22 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw23 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw24 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw25 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw26 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw27 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw28 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw29 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw3 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw30 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw31 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw4 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw5 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw6 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw7 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw8 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  reg [15:0] iw9 = 16'h0000;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:263" *)
  reg [7:0] mask0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:231" *)
  reg [4:0] next_pc0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:64" *)
  reg [7:0] osr = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:67" *)
  reg [2:0] out_pin = 3'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:53" *)
  output [4:0] pc;
  reg [4:0] pc = 5'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/.venv/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:40" *)
  input run;
  wire run;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  reg [7:0] rx0 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  reg [7:0] rx1 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  reg [7:0] rx2 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  reg [7:0] rx3 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:51" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:52" *)
  output rx_empty;
  wire rx_empty;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:117" *)
  reg [2:0] rx_n = 3'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:115" *)
  reg [1:0] rx_r = 2'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:50" *)
  input rx_re;
  wire rx_re;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:116" *)
  reg [1:0] rx_w = 2'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:230" *)
  reg stall0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  reg [7:0] tx0 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  reg [7:0] tx1 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  reg [7:0] tx2 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  reg [7:0] tx3 = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:48" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:49" *)
  output tx_full;
  wire tx_full;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:114" *)
  reg [2:0] tx_n = 3'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:112" *)
  reg [1:0] tx_r = 2'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:113" *)
  reg [1:0] tx_w = 2'h0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:47" *)
  input tx_we;
  wire tx_we;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:62" *)
  reg [7:0] x = 8'h00;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:63" *)
  reg [7:0] y = 8'h00;
  assign tx_full = tx_n == (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:119" *) 3'h4;
  assign rx_empty = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:120" *) rx_n;
  assign \$1  = tx_n != (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:136" *) 3'h4;
  assign host_tx = tx_we & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:136" *) \$1 ;
  assign \$2  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:137" *) rx_n;
  assign host_rx = rx_re & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:137" *) \$2 ;
  assign \$3  = gpio_oe[0] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[0] : gpio_in[0];
  assign \$4  = gpio_oe[1] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[1] : gpio_in[1];
  assign \$5  = gpio_oe[2] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[2] : gpio_in[2];
  assign \$6  = gpio_oe[3] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[3] : gpio_in[3];
  assign \$7  = gpio_oe[4] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[4] : gpio_in[4];
  assign \$8  = gpio_oe[5] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[5] : gpio_in[5];
  assign \$9  = gpio_oe[6] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[6] : gpio_in[6];
  assign \$10  = gpio_oe[7] ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:161" *) gpio_out[7] : gpio_in[7];
  assign \$11  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:232" *) delay_ctr;
  assign \$12  = pc + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:236" *) 1'h1;
  assign \$13  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:243" *) x;
  assign \$14  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:246" *) x;
  assign \$15  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:250" *) y;
  assign \$16  = eff >> in_pin;
  assign \$17  = eff >> instr[3:0];
  assign \$18  = \$17  != (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:259" *) instr[4];
  assign \$19  = 1'h1 << (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:264" *) out_pin;
  assign \$20  = instr[7:5] == (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:277" *) 1'h1;
  assign \$21  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:278" *) tx_n;
  assign \$22  = rx_n == (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:284" *) 3'h4;
  assign \$23  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:101" *) run;
  assign \$24  = imem_we & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:101" *) \$23 ;
  assign \$25  = tx_w + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:142" *) 1'h1;
  assign \$26  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:144" *) do_pull;
  assign \$27  = host_tx & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:144" *) \$26 ;
  assign \$28  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:146" *) host_tx;
  assign \$29  = \$28  & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:146" *) do_pull;
  assign \$30  = tx_n + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:145" *) 1'h1;
  assign \$31  = tx_n - (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:147" *) 1'h1;
  assign \$32  = tx_r + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:149" *) 1'h1;
  assign \$33  = rx_r + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:151" *) 1'h1;
  assign \$34  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:152" *) do_push;
  assign \$35  = host_rx & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:152" *) \$34 ;
  assign \$36  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:154" *) host_rx;
  assign \$37  = \$36  & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:154" *) do_push;
  assign \$38  = rx_n - (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:153" *) 1'h1;
  assign \$39  = rx_n + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:155" *) 1'h1;
  assign \$40  = rx_w + (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:157" *) 1'h1;
  assign \$41  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:232" *) delay_ctr;
  assign \$42  = delay_ctr - (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:233" *) 1'h1;
  assign \$43  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:246" *) x;
  assign \$44  = x - (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:247" *) 1'h1;
  assign \$45  = | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:250" *) y;
  assign \$46  = y - (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:251" *) 1'h1;
  assign \$47  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:262" *) instr[7:5];
  assign \$48  = \$47  ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:262" *) osr[0] : osr[7];
  assign \$49  = gpio_out | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:265" *) mask0;
  assign \$50  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:265" *) mask0;
  assign \$51  = gpio_out & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:265" *) \$50 ;
  assign \$52  = \$48  ? (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:265" *) \$49  : \$51 ;
  assign \$53  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:266" *) instr[7:5];
  assign \$56  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:272" *) instr[7:5];
  assign \$57  = eff >> in_pin;
  assign \$58  = eff >> in_pin;
  assign \$59  = instr[7:5] == (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:277" *) 1'h1;
  assign \$60  = ! (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:278" *) tx_n;
  assign \$62  = rx_n == (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:284" *) 3'h4;
  assign \$63  = 1'h1 << (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:300" *) instr[2:0];
  assign \$64  = gpio_out | (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:300" *) \$63 ;
  assign \$65  = 1'h1 << (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:302" *) instr[2:0];
  assign \$66  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:302" *) \$65 ;
  assign \$67  = gpio_out & (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:302" *) \$66 ;
  assign \$68  = ~ (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:309" *) stall0;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw0 <= \$69 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw1 <= \$70 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw2 <= \$71 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw3 <= \$72 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw4 <= \$73 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw5 <= \$74 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw6 <= \$75 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw7 <= \$76 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw8 <= \$77 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw9 <= \$78 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw10 <= \$79 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw11 <= \$80 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw12 <= \$81 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw13 <= \$82 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw14 <= \$83 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw15 <= \$84 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw16 <= \$85 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw17 <= \$86 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw18 <= \$87 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw19 <= \$88 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw20 <= \$89 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw21 <= \$90 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw22 <= \$91 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw23 <= \$92 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw24 <= \$93 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw25 <= \$94 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw26 <= \$95 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw27 <= \$96 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw28 <= \$97 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw29 <= \$98 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw30 <= \$99 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:69" *)
  always @(posedge clk)
    iw31 <= \$100 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  always @(posedge clk)
    tx0 <= \$101 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  always @(posedge clk)
    tx1 <= \$102 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  always @(posedge clk)
    tx2 <= \$103 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:110" *)
  always @(posedge clk)
    tx3 <= \$104 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:113" *)
  always @(posedge clk)
    tx_w <= \$105 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:114" *)
  always @(posedge clk)
    tx_n <= \$106 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:112" *)
  always @(posedge clk)
    tx_r <= \$107 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:115" *)
  always @(posedge clk)
    rx_r <= \$108 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:117" *)
  always @(posedge clk)
    rx_n <= \$109 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:116" *)
  always @(posedge clk)
    rx_w <= \$110 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:66" *)
  always @(posedge clk)
    delay_ctr <= \$111 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:62" *)
  always @(posedge clk)
    x <= \$112 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:63" *)
  always @(posedge clk)
    y <= \$113 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:42" *)
  always @(posedge clk)
    gpio_out <= \$114 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:64" *)
  always @(posedge clk)
    osr <= \$115 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:65" *)
  always @(posedge clk)
    isr <= \$116 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  always @(posedge clk)
    rx0 <= \$117 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  always @(posedge clk)
    rx1 <= \$118 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  always @(posedge clk)
    rx2 <= \$119 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:111" *)
  always @(posedge clk)
    rx3 <= \$120 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:43" *)
  always @(posedge clk)
    gpio_oe <= \$121 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:67" *)
  always @(posedge clk)
    out_pin <= \$122 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:68" *)
  always @(posedge clk)
    in_pin <= \$123 ;
  (* src = "/home/wsb/Documents/Binaries/jane_street/generator/loom/rtl.py:53" *)
  always @(posedge clk)
    pc <= \$124 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (pc)
      5'h00:
          instr = iw0;
      5'h01:
          instr = iw1;
      5'h02:
          instr = iw2;
      5'h03:
          instr = iw3;
      5'h04:
          instr = iw4;
      5'h05:
          instr = iw5;
      5'h06:
          instr = iw6;
      5'h07:
          instr = iw7;
      5'h08:
          instr = iw8;
      5'h09:
          instr = iw9;
      5'h0a:
          instr = iw10;
      5'h0b:
          instr = iw11;
      5'h0c:
          instr = iw12;
      5'h0d:
          instr = iw13;
      5'h0e:
          instr = iw14;
      5'h0f:
          instr = iw15;
      5'h10:
          instr = iw16;
      5'h11:
          instr = iw17;
      5'h12:
          instr = iw18;
      5'h13:
          instr = iw19;
      5'h14:
          instr = iw20;
      5'h15:
          instr = iw21;
      5'h16:
          instr = iw22;
      5'h17:
          instr = iw23;
      5'h18:
          instr = iw24;
      5'h19:
          instr = iw25;
      5'h1a:
          instr = iw26;
      5'h1b:
          instr = iw27;
      5'h1c:
          instr = iw28;
      5'h1d:
          instr = iw29;
      5'h1e:
          instr = iw30;
      5'h1f:
          instr = iw31;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (rx_r)
      2'h0:
          rx_data = rx0;
      2'h1:
          rx_data = rx1;
      2'h2:
          rx_data = rx2;
      2'h3:
          rx_data = rx3;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (tx_r)
      2'h0:
          \$61  = tx0;
      2'h1:
          \$61  = tx1;
      2'h2:
          \$61  = tx2;
      2'h3:
          \$61  = tx3;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    stall0 = 1'h0;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$11 ) begin
      end else begin
        stall0 = 1'h0;
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              if (\$18 ) begin
                stall0 = 1'h1;
              end
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$20 ) begin
                if (\$21 ) begin
                  stall0 = 1'h1;
                end
              end else begin
                if (\$22 ) begin
                  stall0 = 1'h1;
                end
              end
        endcase
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    next_pc0 = 5'h00;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$11 ) begin
      end else begin
        next_pc0 = \$12 [4:0];
        casez (instr[15:13])
          3'h0:
              casez (instr[7:5])
                3'h0:
                    next_pc0 = instr[4:0];
                3'h1:
                    if (\$13 ) begin
                      next_pc0 = instr[4:0];
                    end
                3'h3:
                    if (\$14 ) begin
                      next_pc0 = instr[4:0];
                    end
                3'h4:
                    if (\$15 ) begin
                      next_pc0 = instr[4:0];
                    end
                3'h5:
                    if (\$16 ) begin
                      next_pc0 = instr[4:0];
                    end
              endcase
        endcase
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    mask0 = 8'h00;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$11 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              mask0 = \$19 ;
        endcase
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    do_pull = 1'h0;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$11 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              if (\$20 ) begin
                (* full_case = 32'd1 *)
                if (\$21 ) begin
                end else begin
                  do_pull = 1'h1;
                end
              end
        endcase
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    do_push = 1'h0;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$11 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$20 ) begin
              end else begin
                (* full_case = 32'd1 *)
                if (\$22 ) begin
                end else begin
                  do_push = 1'h1;
                end
              end
        endcase
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$69  = iw0;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            \$69  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$69  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$70  = iw1;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            \$70  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$70  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$71  = iw2;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            \$71  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$71  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$72  = iw3;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            \$72  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$72  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$73  = iw4;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            \$73  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$73  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$74  = iw5;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            \$74  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$74  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$75  = iw6;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            \$75  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$75  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$76  = iw7;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            \$76  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$76  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$77  = iw8;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            \$77  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$77  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$78  = iw9;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            \$78  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$78  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$79  = iw10;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            \$79  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$79  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$80  = iw11;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            \$80  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$80  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$81  = iw12;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            \$81  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$81  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$82  = iw13;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            \$82  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$82  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$83  = iw14;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            \$83  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$83  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$84  = iw15;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            \$84  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$84  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$85  = iw16;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            \$85  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$85  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$86  = iw17;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            \$86  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$86  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$87  = iw18;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            \$87  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$87  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$88  = iw19;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            \$88  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$88  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$89  = iw20;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            \$89  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$89  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$90  = iw21;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            \$90  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$90  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$91  = iw22;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            \$91  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$91  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$92  = iw23;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            \$92  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$92  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$93  = iw24;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            \$93  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$93  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$94  = iw25;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            \$94  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$94  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$95  = iw26;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            \$95  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$95  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$96  = iw27;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            /* empty */;
        5'h1b:
            \$96  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$96  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$97  = iw28;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            /* empty */;
        5'h1b:
            /* empty */;
        5'h1c:
            \$97  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$97  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$98  = iw29;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            /* empty */;
        5'h1b:
            /* empty */;
        5'h1c:
            /* empty */;
        5'h1d:
            \$98  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$98  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$99  = iw30;
    if (\$24 ) begin
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            /* empty */;
        5'h1b:
            /* empty */;
        5'h1c:
            /* empty */;
        5'h1d:
            /* empty */;
        5'h1e:
            \$99  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$99  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$100  = iw31;
    if (\$24 ) begin
      (* full_case = 32'd1 *)
      casez (imem_waddr)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            /* empty */;
        5'h09:
            /* empty */;
        5'h0a:
            /* empty */;
        5'h0b:
            /* empty */;
        5'h0c:
            /* empty */;
        5'h0d:
            /* empty */;
        5'h0e:
            /* empty */;
        5'h0f:
            /* empty */;
        5'h10:
            /* empty */;
        5'h11:
            /* empty */;
        5'h12:
            /* empty */;
        5'h13:
            /* empty */;
        5'h14:
            /* empty */;
        5'h15:
            /* empty */;
        5'h16:
            /* empty */;
        5'h17:
            /* empty */;
        5'h18:
            /* empty */;
        5'h19:
            /* empty */;
        5'h1a:
            /* empty */;
        5'h1b:
            /* empty */;
        5'h1c:
            /* empty */;
        5'h1d:
            /* empty */;
        5'h1e:
            /* empty */;
        5'h1f:
            \$100  = imem_wdata;
      endcase
    end
    if (rst) begin
      \$100  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$101  = tx0;
    if (host_tx) begin
      casez (tx_w)
        2'h0:
            \$101  = tx_data;
      endcase
    end
    if (rst) begin
      \$101  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$102  = tx1;
    if (host_tx) begin
      casez (tx_w)
        2'h0:
            /* empty */;
        2'h1:
            \$102  = tx_data;
      endcase
    end
    if (rst) begin
      \$102  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$103  = tx2;
    if (host_tx) begin
      casez (tx_w)
        2'h0:
            /* empty */;
        2'h1:
            /* empty */;
        2'h2:
            \$103  = tx_data;
      endcase
    end
    if (rst) begin
      \$103  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$104  = tx3;
    if (host_tx) begin
      (* full_case = 32'd1 *)
      casez (tx_w)
        2'h0:
            /* empty */;
        2'h1:
            /* empty */;
        2'h2:
            /* empty */;
        2'h3:
            \$104  = tx_data;
      endcase
    end
    if (rst) begin
      \$104  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$105  = tx_w;
    if (host_tx) begin
      \$105  = \$25 [1:0];
    end
    if (rst) begin
      \$105  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$106  = tx_n;
    if (\$27 ) begin
      \$106  = \$30 [2:0];
    end else if (\$29 ) begin
      \$106  = \$31 [2:0];
    end
    if (rst) begin
      \$106  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$107  = tx_r;
    if (do_pull) begin
      \$107  = \$32 [1:0];
    end
    if (rst) begin
      \$107  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$108  = rx_r;
    if (host_rx) begin
      \$108  = \$33 [1:0];
    end
    if (rst) begin
      \$108  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$109  = rx_n;
    if (\$35 ) begin
      \$109  = \$38 [2:0];
    end else if (\$37 ) begin
      \$109  = \$39 [2:0];
    end
    if (rst) begin
      \$109  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$110  = rx_w;
    if (do_push) begin
      \$110  = \$40 [1:0];
    end
    if (rst) begin
      \$110  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$111  = delay_ctr;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
        \$111  = \$42 [4:0];
      end else begin
        if (\$68 ) begin
          \$111  = instr[12:8];
        end
      end
    end
    if (rst) begin
      \$111  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$112  = x;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h3:
                    if (\$43 ) begin
                      \$112  = \$44 [7:0];
                    end
              endcase
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h2:
                    \$112  = { 3'h0, instr[4:0] };
              endcase
        endcase
      end
    end
    if (rst) begin
      \$112  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$113  = y;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h3:
                    /* empty */;
                3'h4:
                    if (\$45 ) begin
                      \$113  = \$46 [7:0];
                    end
              endcase
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h2:
                    /* empty */;
                3'h3:
                    \$113  = { 3'h0, instr[4:0] };
              endcase
        endcase
      end
    end
    if (rst) begin
      \$113  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$114  = gpio_out;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              \$114  = \$52 ;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              casez (instr[7:5])
                3'h0:
                    \$114 [4:0] = instr[4:0];
                3'h1:
                    /* empty */;
                3'h2:
                    /* empty */;
                3'h3:
                    /* empty */;
                3'h4:
                    \$114  = \$64 ;
                3'h5:
                    \$114  = \$67 ;
              endcase
        endcase
      end
    end
    if (rst) begin
      \$114  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$115  = osr;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              (* full_case = 32'd1 *)
              if (\$53 ) begin
                \$115  = \$54 ;
              end else begin
                \$115  = \$55 [7:0];
              end
          3'h2:
              /* empty */;
          3'h4:
              if (\$59 ) begin
                (* full_case = 32'd1 *)
                if (\$60 ) begin
                end else begin
                  \$115  = \$61 ;
                end
              end
        endcase
      end
    end
    if (rst) begin
      \$115  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$116  = isr;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              (* full_case = 32'd1 *)
              if (\$56 ) begin
                \$116  = { \$57 , isr[7:1] };
              end else begin
                \$116  = { isr[6:0], \$58  };
              end
        endcase
      end
    end
    if (rst) begin
      \$116  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$117  = rx0;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$59 ) begin
              end else begin
                (* full_case = 32'd1 *)
                if (\$62 ) begin
                end else begin
                  casez (rx_w)
                    2'h0:
                        \$117  = isr;
                  endcase
                end
              end
        endcase
      end
    end
    if (rst) begin
      \$117  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$118  = rx1;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$59 ) begin
              end else begin
                (* full_case = 32'd1 *)
                if (\$62 ) begin
                end else begin
                  casez (rx_w)
                    2'h0:
                        /* empty */;
                    2'h1:
                        \$118  = isr;
                  endcase
                end
              end
        endcase
      end
    end
    if (rst) begin
      \$118  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$119  = rx2;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$59 ) begin
              end else begin
                (* full_case = 32'd1 *)
                if (\$62 ) begin
                end else begin
                  casez (rx_w)
                    2'h0:
                        /* empty */;
                    2'h1:
                        /* empty */;
                    2'h2:
                        \$119  = isr;
                  endcase
                end
              end
        endcase
      end
    end
    if (rst) begin
      \$119  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$120  = rx3;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              (* full_case = 32'd1 *)
              if (\$59 ) begin
              end else begin
                (* full_case = 32'd1 *)
                if (\$62 ) begin
                end else begin
                  (* full_case = 32'd1 *)
                  casez (rx_w)
                    2'h0:
                        /* empty */;
                    2'h1:
                        /* empty */;
                    2'h2:
                        /* empty */;
                    2'h3:
                        \$120  = isr;
                  endcase
                end
              end
        endcase
      end
    end
    if (rst) begin
      \$120  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$121  = gpio_oe;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    \$121 [4:0] = instr[4:0];
              endcase
        endcase
      end
    end
    if (rst) begin
      \$121  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$122  = out_pin;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h2:
                    /* empty */;
                3'h3:
                    /* empty */;
                3'h4:
                    /* empty */;
                3'h5:
                    /* empty */;
                3'h6:
                    \$122  = instr[2:0];
              endcase
        endcase
      end
    end
    if (rst) begin
      \$122  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$123  = in_pin;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        casez (instr[15:13])
          3'h0:
              /* empty */;
          3'h1:
              /* empty */;
          3'h3:
              /* empty */;
          3'h2:
              /* empty */;
          3'h4:
              /* empty */;
          3'h6:
              (* full_case = 32'd1 *)
              casez (instr[7:5])
                3'h0:
                    /* empty */;
                3'h1:
                    /* empty */;
                3'h2:
                    /* empty */;
                3'h3:
                    /* empty */;
                3'h4:
                    /* empty */;
                3'h5:
                    /* empty */;
                3'h6:
                    /* empty */;
                3'h7:
                    \$123  = instr[2:0];
              endcase
        endcase
      end
    end
    if (rst) begin
      \$123  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$124  = pc;
    if (run) begin
      (* full_case = 32'd1 *)
      if (\$41 ) begin
      end else begin
        if (\$68 ) begin
          \$124  = next_pc0;
        end
      end
    end
    if (rst) begin
      \$124  = 5'h00;
    end
  end
  assign do_pull0 = do_pull;
  assign do_push0 = do_push;
  assign eff[7] = \$10 ;
  assign eff[6] = \$9 ;
  assign eff[5] = \$8 ;
  assign eff[4] = \$7 ;
  assign eff[3] = \$6 ;
  assign eff[2] = \$5 ;
  assign eff[1] = \$4 ;
  assign eff[0] = \$3 ;
  assign \$54  = { 1'h0, osr[7:1] };
  assign \$55  = { osr, 1'h0 };
endmodule
